services:
  backend:
    build:
      context: backend_core_graph
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  ai_service:
    build:
      context: ./python_scripts
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      app-network:

  frontend:
    build:
      context: gui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - ai_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge